### ISSUE TITLE
LineChart-2当数据少于3个的时候，绘制不出，并且无响应

### ISSUE THREAD

**Issue by pengchifei** [foolsong/EasyCharts#2]
LineChart-2当数据少于3个的时候，绘制不出，并且无响应
- (void)scrollToRightmostCell {

    CGFloat offsetX = 0.0;
    if ([[self pointModelList] count] < 3) {
        offsetX = 0.2 * 2;
    } else {
        offsetX = ([[self pointModelList] count] - 3) * self.cellWidth + 0.2 * 2;
    }
    self.contentOffset = CGPointMake(offsetX, 0);
    self.currentIndex = [[self pointModelList] count] - 1;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)),
                   dispatch_get_main_queue(), ^{
                       [self setupCellSelected];
                   });
    
    [self didSelectItemAtIndexPath:[NSIndexPath
                                    indexPathForRow:([self.pointModelList count] - 1)
                                    inSection:0]];
}

**Comment by foolsong** [comment]
问题已经修复，感谢您提出的问题。
